project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: images/favicon-32x32.ico

  navbar:
    left:
      - href: "#"
        icon: ""                # we’ll override with an <img> in content below
        text: |
          <img src="images/bcl_logo_trans.png" class="navbar-logo" alt="Logo">
      - href: index.qmd
        text: "home"
      - href: people.qmd
        text: "people"
      - href: research.qmd
        text: "research"
      - href: publications.qmd
        text: "publications"
      - href: funding.qmd
        text: "funding"
      - href: about.qmd
        text: "about"
    right:
      - href: https://facebook.com
        icon: facebook    # Quarto knows some built-in icons
      - href: https://blueskyweb.xyz
        text: Bluesky     # or provide your own icon/text

format:
  html:
    css: styles.css
    toc: false


