project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: "images/favicon_io/favicon.ico"
  navbar:
    logo: "images/headers/nav_logo.png"
    right:
      - href: index.qmd
        text: home
      - text: people
        menu: 
          - text: "All members"
            href: people.qmd
          - text: "Patrick Kelley (Lab head)"
            href: patrick_kelley.qmd
      - href: "research/research.qmd"
        text: research
      - href: "join/join.qmd"
        text: join
      - href: "publications.qmd"
        text: publications
      - icon: facebook
        href: "https://www.facebook.com/profile.php?id=61576968269090"
      - icon: bluesky
        href: "https://bsky.app/profile/bcl-research.bsky.social"
        aria-label: "Follow on Bluesky"

collections:
  ind_profiles:
    output: false
  research_profiles:
    output: false
    
format:
  html:
    theme:
      - cosmo
    sidebar: true
    css: styles.css
    toc: false
    include-in-header: _includes/fonts.html
    include-after-body: _includes/footer.html
    link-external-newwindow: true

editor: visual

